# Generated by Django 3.2.9 on 2022-03-09 14:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='village',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('village_name', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='famous',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('famous_food', models.CharField(db_index=True, max_length=200)),
                ('famous_place', models.CharField(db_index=True, max_length=200)),
                ('famous_fruit', models.CharField(db_index=True, max_length=200)),
                ('famous_handicraft', models.CharField(db_index=True, max_length=200)),
                ('name_of_village', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tourism.village')),
            ],
        ),
    ]
