# Generated by Django 4.0.3 on 2022-03-09 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tourism', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.TextField()),
            ],
        ),
        migrations.RemoveField(
            model_name='famous',
            name='famous_food',
        ),
        migrations.RemoveField(
            model_name='famous',
            name='famous_fruit',
        ),
        migrations.RemoveField(
            model_name='famous',
            name='famous_handicraft',
        ),
        migrations.RemoveField(
            model_name='famous',
            name='famous_place',
        ),
        migrations.RemoveField(
            model_name='famous',
            name='name_of_village',
        ),
        migrations.AddField(
            model_name='famous',
            name='category',
            field=models.TextField(default='food'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famous',
            name='dislike',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famous',
            name='item',
            field=models.TextField(default='jalebi'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='famous',
            name='like',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='village',
        ),
        migrations.AddField(
            model_name='famous',
            name='location',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='tourism.location'),
        ),
    ]
